# Setup
title:               Trevo525
tagline:             'Trevor Vances Github Page'
description:         'A place for Trevor to organize pages, guides, and blog posts.'
url:                 http://localhost:4000/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Trevor Vance
  url:               https://Trevo525.github.io
  email:             trevorvance525@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
github_url:          https://github.com/Trevo525
linkedin_url:        https://www.linkedin.com/in/trevo525/
